import type { AdoptableDog } from "./types";

export const ADOPTABLE_DOGS: AdoptableDog[] = [
  // ── tlv-dog-haven (center) ──
  {
    id: "tlv-dog-haven-luna-2026",
    name: "לונה",
    age: 4,
    ageGroup: "adult",
    sex: "female",
    neutered: true,
    size: "medium",
    breedSlug: "border-collie",
    breedDisplay: "בורדר קולי מעורב",
    weightKg: 18,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e4/Border_Collie_600.jpg",
    shelterId: "tlv-dog-haven",
    region: "center",
    description: "לונה הגיעה אלינו אחרי שמצאנו אותה משוטטת ליד נמל תל אביב. היא כלבה חכמה וסקרנית שאוהבת לשחק עם כדור ולחקור פינות חדשות. מחפשת בית עם גינה קטנה ובעל שיוכל לרוץ איתה בבוקר.",
    goodWith: ["kids", "dogs"],
    tags: ["אנרגיה גבוהה", "אוהב לשחק", "צריך אילוף"],
    dateAvailable: "2026-03-15",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "tlv-dog-haven-max-2026",
    name: "מקס",
    age: 2,
    ageGroup: "young",
    sex: "male",
    neutered: true,
    size: "large",
    breedSlug: "labrador",
    breedDisplay: "לברדור מעורב",
    weightKg: 28,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/34/Labrador_on_Quantock_%282175262184%29.jpg",
    shelterId: "tlv-dog-haven",
    region: "center",
    description: "מקס הוא צעיר שמח ואנרגטי שנמסר לידינו כשבעליו עבר לחו\"ל. הוא מתחבר מהר לאנשים חדשים ויודע לשבת ולתת יד. אוהב לשחות בים ויאהב משפחה פעילה.",
    goodWith: ["kids", "dogs", "cats"],
    tags: ["ידידותי", "אוהב מים", "קל לאילוף"],
    dateAvailable: "2026-02-20",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "tlv-dog-haven-bella-2026",
    name: "בלה",
    age: 0.4,
    ageGroup: "puppy",
    sex: "female",
    neutered: false,
    size: "small",
    breedDisplay: "תערובת",
    weightKg: 3,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/34/Labrador_on_Quantock_%282175262184%29.jpg",
    shelterId: "tlv-dog-haven",
    region: "center",
    description: "בלה היא גורה קטנה וחייכנית שנמצאה בשקית ליד הפארק. היא עדיין לומדת את הכללים אבל מחזירה אהבה כפולה. מתאימה לדירה עם בעלים סבלניים שיגדלו אותה מגיל צעיר.",
    goodWith: ["kids", "cats"],
    tags: ["גורה", "חמוד", "מלא חיים"],
    dateAvailable: "2026-04-10",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "tlv-dog-haven-cooper-2026",
    name: "קופר",
    age: 5,
    ageGroup: "adult",
    sex: "male",
    neutered: true,
    size: "large",
    breedSlug: "golden",
    breedDisplay: "גולדן רטריבר מעורב",
    weightKg: 33,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/bd/Golden_Retriever_Dukedestiny01_drvd.jpg",
    shelterId: "tlv-dog-haven",
    region: "center",
    description: "קופר הוא כלב רגוע ומאוזן שאוהב לשכב לצד אנשים ולקבל חיבוקים. הוא היה כלב משפחה ונמסר עקב מעבר דירה. מסתדר מצוין עם ילדים ואחד מהכלבים הכי ידידותיים שיש לנו.",
    goodWith: ["kids", "dogs", "cats", "small-pets"],
    tags: ["רגוע", "ידידותי", "אוהב ילדים"],
    dateAvailable: "2026-02-12",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "tlv-dog-haven-daisy-2026",
    name: "דייזי",
    age: 8,
    ageGroup: "senior",
    sex: "female",
    neutered: true,
    size: "medium",
    breedDisplay: "תערובת",
    weightKg: 15,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d0/German_Shepherd_-_DSC_0346_%2810096362833%29.jpg",
    shelterId: "tlv-dog-haven",
    region: "center",
    description: "דייזי היא גברת מבוגרת ומפונקת שאוהבת שינה ארוכה על הכנסת ותה לצד הבעלים. לא צריכה הרבה פעילות, רק הרבה אהבה וקרבה. מושלמת למשפחה שמחפשת כלב שקט ונאמן.",
    goodWith: ["cats"],
    tags: ["שקט", "מבוגר", "מחבב נינוחות"],
    dateAvailable: "2026-03-01",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "tlv-dog-haven-charlie-2026",
    name: "צ'רלי",
    age: 1.5,
    ageGroup: "young",
    sex: "male",
    neutered: true,
    size: "medium",
    breedSlug: "beagle",
    breedDisplay: "ביגל מעורב",
    weightKg: 14,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/55/Beagle_600.jpg",
    shelterId: "tlv-dog-haven",
    region: "center",
    description: "צ'רלי כלב סקרן עם חוש ריח מפותח שאוהב לחקור כל שביל. הוא נמסר כשבעליו לא יכל עוד להתמודד עם האנרגיה שלו. עם אילוף נכון יהיה שותף מעולה לטיולים.",
    goodWith: ["kids", "dogs"],
    tags: ["סקרן", "אנרגטי", "אוהב טיולים"],
    dateAvailable: "2026-04-22",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  // ── sharon-rescue (center) ──
  {
    id: "sharon-rescue-lucy-2026",
    name: "לוסי",
    age: 3,
    ageGroup: "adult",
    sex: "female",
    neutered: true,
    size: "small",
    breedSlug: "cocker",
    breedDisplay: "קוקר ספניאל מעורב",
    weightKg: 11,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/%22Bill%22_-_Cocker_spaniel_anglais_2.JPG/3840px-%22Bill%22_-_Cocker_spaniel_anglais_2.JPG",
    shelterId: "sharon-rescue",
    region: "center",
    description: "לוסי היא כלבה עם עיניים מדהימות ונפש ענוגה. הגיעה אלינו אחרי שבעלתה אושפזה ולא יכלה לטפל בה. אוהבת לשבת בחיק ולהאזין למוזיקה. תתאים לבית שקט.",
    goodWith: ["cats", "small-pets"],
    tags: ["עדין", "חביב", "אוהב חיבוקים"],
    dateAvailable: "2026-03-20",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "sharon-rescue-buddy-2026",
    name: "באדי",
    age: 1,
    ageGroup: "young",
    sex: "male",
    neutered: true,
    size: "large",
    breedSlug: "german-shepherd",
    breedDisplay: "רועה גרמני מעורב",
    weightKg: 30,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d0/German_Shepherd_-_DSC_0346_%2810096362833%29.jpg",
    shelterId: "sharon-rescue",
    region: "center",
    description: "באדי הוא צעיר עם הרבה פוטנציאל שמחפש מנהיג. הגיע כגור ממשפחה שלא יכלה לגדל אותו. חכם מאוד וזקוק לאילוף עקבי. עם הכוונה נכונה יהיה כלב מרשים ונאמן.",
    goodWith: ["kids"],
    tags: ["חכם", "זקוק לאילוף", "נאמן"],
    dateAvailable: "2026-05-01",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "sharon-rescue-roxy-2026",
    name: "רוקסי",
    age: 4,
    ageGroup: "adult",
    sex: "female",
    neutered: true,
    size: "medium",
    breedDisplay: "תערובת",
    weightKg: 17,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/bd/Golden_Retriever_Dukedestiny01_drvd.jpg",
    shelterId: "sharon-rescue",
    region: "center",
    description: "רוקסי כלבה בעלת אופי חזק ועצמאי, אבל לאלה שזוכים לאמונה שלה — היא נאמנה לכל החיים. אוהבת ריצה בשדות פתוחים ומשחקי חיפוש. מתאימה לבעלים עם ניסיון.",
    goodWith: ["dogs"],
    tags: ["עצמאי", "אנרגטי", "צריך ניסיון"],
    dateAvailable: "2026-02-28",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "sharon-rescue-oscar-2026",
    name: "אוסקר",
    age: 6,
    ageGroup: "adult",
    sex: "male",
    neutered: true,
    size: "giant",
    breedSlug: "bernese",
    breedDisplay: "ברנזה מעורב",
    weightKg: 48,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/3-BerneseMountainDogInGrass.jpg/3840px-3-BerneseMountainDogInGrass.jpg",
    shelterId: "sharon-rescue",
    region: "center",
    description: "אוסקר הוא ענק עם לב זהב. הגיע אלינו עקב בעיות כלכליות של בעליו הקודמים. רגוע ומאוזן, אוהב לשכב ליד השטיח ולהיות חלק מהמשפחה. זקוק לבית עם מקום.",
    goodWith: ["kids", "dogs", "cats"],
    tags: ["רגוע", "ענק חביב", "ידידותי"],
    dateAvailable: "2026-03-08",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "sharon-rescue-molly-2026",
    name: "מולי",
    age: 2,
    ageGroup: "young",
    sex: "female",
    neutered: true,
    size: "toy",
    breedSlug: "chihuahua",
    breedDisplay: "צ'יוואווה מעורב",
    weightKg: 3,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4c/Chihuahua1_bvdb.jpg",
    shelterId: "sharon-rescue",
    region: "center",
    description: "מולי היא כלבה קטנה בעלת ביטחון עצמי גדול. הגיעה מבית שלא יכל לתת לה את תשומת הלב שהיא צריכה. עוקבת אחרי בעליה לכל מקום ואוהבת לישון מתחת לשמיכה.",
    goodWith: ["cats", "small-pets"],
    tags: ["קטן", "חייכן", "מלא אישיות"],
    dateAvailable: "2026-04-05",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "sharon-rescue-franki-2026",
    name: "פרנקי",
    age: 9,
    ageGroup: "senior",
    sex: "male",
    neutered: true,
    size: "medium",
    breedDisplay: "תערובת",
    weightKg: 16,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/18/2008-07-28_Dog_at_Frolick_Field.jpg",
    shelterId: "sharon-rescue",
    region: "center",
    description: "פרנקי הוא כלב ותיק שעבר הרבה בחייו אבל שמר על נפש טובה. זקן ורגוע, מסתפק בטיול קצר ובמנוחה על הספה. יאהב בית שקט עם אנשים מבוגרים שמעריכים חברה.",
    goodWith: ["cats"],
    tags: ["מבוגר", "שקט", "אוהב נינוחות"],
    dateAvailable: "2026-02-15",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "sharon-rescue-rosie-2026",
    name: "רוסי",
    age: 1.5,
    ageGroup: "young",
    sex: "female",
    neutered: false,
    size: "medium",
    breedSlug: "vizsla",
    breedDisplay: "ויז'לה מעורב",
    weightKg: 20,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/2d/Wy%C5%BCe%C5%82_w%C4%99gierski_g%C5%82adkow%C5%82osy_500.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    shelterId: "sharon-rescue",
    region: "center",
    description: "רוסי כלבה רזה ומהירה עם אנרגיה של ספורטאית. נמצאה קשורה ליד בניין נטוש ומאז לא מפסיקה לזוז. מחפשת בעל שרץ או רוכב אופניים שיוכל לתת לה שחרור אנרגיה יומיומי.",
    goodWith: ["dogs", "kids"],
    tags: ["אנרגיה גבוהה", "מהיר", "אוהב ריצה"],
    dateAvailable: "2026-05-10",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "sharon-rescue-skip-2026",
    name: "סקיפ",
    age: 0.3,
    ageGroup: "puppy",
    sex: "male",
    neutered: false,
    size: "medium",
    breedDisplay: "תערובת",
    weightKg: 4,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/34/Labrador_on_Quantock_%282175262184%29.jpg",
    shelterId: "sharon-rescue",
    region: "center",
    description: "סקיפ גור שמח ומפזזחל שנמצא ביחד עם שלושה אחים. הוא הגור הפעיל ביותר מהלקוח ותמיד הראשון לבוא לברך אורחים. יתאים לבית פעיל עם ילדים אנרגטיים.",
    goodWith: ["kids", "dogs"],
    tags: ["גורה", "שובב", "מלא חיים"],
    dateAvailable: "2026-05-15",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  // ── noaf-galil (north) ──
  {
    id: "noaf-galil-nima-2026",
    name: "נימה",
    age: 3,
    ageGroup: "adult",
    sex: "female",
    neutered: true,
    size: "large",
    breedSlug: "husky",
    breedDisplay: "האסקי מעורב",
    weightKg: 26,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8b/Husky_L.jpg",
    shelterId: "noaf-galil",
    region: "north",
    description: "נימה הגיעה מהצפון הקיצוני עם עיניים כחולות כשמיים ורוח חופשית. היא אוהבת ריצה בין העצים ומשחקים בשלג כשיש. בבית רגועה ונינוחה אבל בחוץ — שיכורת חיים.",
    goodWith: ["dogs"],
    tags: ["אנרגיה גבוהה", "אוהב קור", "עצמאי"],
    dateAvailable: "2026-03-12",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "noaf-galil-alma-2026",
    name: "אלמה",
    age: 5,
    ageGroup: "adult",
    sex: "female",
    neutered: true,
    size: "medium",
    breedSlug: "canaan",
    breedDisplay: "כלב כנעני מעורב",
    weightKg: 18,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/fe/CanaanDogChakede.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    shelterId: "noaf-galil",
    region: "north",
    description: "אלמה היא כלבה ישראלית מקורית שחיה בשטח הפתוח בגליל לפני שאומצה לזמן קצר ואז חזרה. היא עצמאית ומגינה על המשפחה, אבל מסתגלת יפה לחיים בבית עם גינה.",
    goodWith: ["kids"],
    tags: ["שמירתי", "עצמאי", "מגן על הבית"],
    dateAvailable: "2026-04-01",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "noaf-galil-fadel-2026",
    name: "פאדל",
    age: 1,
    ageGroup: "young",
    sex: "male",
    neutered: true,
    size: "small",
    breedSlug: "jack-russell",
    breedDisplay: "ג'ק ראסל מעורב",
    weightKg: 7,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f1/Jack_Russell_Terrier_1.jpg",
    shelterId: "noaf-galil",
    region: "north",
    description: "פאדל הוא רקיד שמחפש דוות. הוא קופץ, מסתובב, ורוצה לשחק כל היום. בדיוק הכלב בשביל משפחה עם ילדים שיהנו מהאנרגיה שלו.",
    goodWith: ["kids", "dogs"],
    tags: ["אנרגטי", "קופצני", "אוהב לשחק"],
    dateAvailable: "2026-02-25",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "noaf-galil-milo-2026",
    name: "מילו",
    age: 2,
    ageGroup: "young",
    sex: "male",
    neutered: true,
    size: "medium",
    breedDisplay: "תערובת",
    weightKg: 16,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/bd/Golden_Retriever_Dukedestiny01_drvd.jpg",
    shelterId: "noaf-galil",
    region: "north",
    description: "מילו נמסר לידינו בגיל שנה על ידי משפחה שהתחרטה על האימוץ. מאז הוא לומד לסמוך שוב על אנשים. הוא חכם וחמוד, וסופסוף מתחיל לאהוב ללכת לטיולים.",
    goodWith: ["kids", "dogs", "cats"],
    tags: ["רגיש", "מחפש בית יציב", "חכם"],
    dateAvailable: "2026-03-25",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "noaf-galil-fox-2026",
    name: "פוקס",
    age: 7,
    ageGroup: "senior",
    sex: "male",
    neutered: true,
    size: "large",
    breedSlug: "doberman",
    breedDisplay: "דוברמן מעורב",
    weightKg: 36,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/ac/Dobermann_handling.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    shelterId: "noaf-galil",
    region: "north",
    description: "פוקס הוא כלב שמירה לשעבר שפרש לגמלאות. הוא רציני ובעל נוכחות, אבל עם הבעלים שלו הוא נמס. אחרי שנים בשמירה מגיע לו בית חמים עם בעל אוהב.",
    goodWith: ["kids"],
    tags: ["כלב שמירה", "רציני", "נאמן"],
    dateAvailable: "2026-04-15",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "noaf-galil-romi-2026",
    name: "רומי",
    age: 0.5,
    ageGroup: "puppy",
    sex: "female",
    neutered: false,
    size: "large",
    breedSlug: "australian-shepherd",
    breedDisplay: "רועה אוסטרלי מעורב",
    weightKg: 8,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Australian_Shepherd_red_bi.JPG/3840px-Australian_Shepherd_red_bi.JPG",
    shelterId: "noaf-galil",
    region: "north",
    description: "רומי גורה צבעונית ומרשימה שנולדה אצלנו בחולת. היא כבר מראה סימני חוכמה וסקרנות אופיינית לגזעה. תגדל לכלב חכם ומחויב לבעליה.",
    goodWith: ["kids", "dogs"],
    tags: ["גורה", "חכם", "צבעוני"],
    dateAvailable: "2026-04-28",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "noaf-galil-izzy-2026",
    name: "איזי",
    age: 4,
    ageGroup: "adult",
    sex: "female",
    neutered: true,
    size: "small",
    breedSlug: "dachshund",
    breedDisplay: "דכשונד מעורב",
    weightKg: 9,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/be/%EB%8B%A5%EC%8A%A4%ED%9B%88%ED%8A%B8%28%EB%8B%A8%EB%AA%A8%EC%A2%85%29_%28Dachshund_%28Short%29%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    shelterId: "noaf-galil",
    region: "north",
    description: "איזי היא נקניקית קטנה עם אישיות גדולה. אוהבת לחפור בחצר ולרדוף אחרי ריחות. נמסרה על ידי זוג שעבר לחו\"ל. מסתדרת מצוין בדירה קטנה כל עוד יוצאים איתה פעמיים ביום.",
    goodWith: ["cats", "kids"],
    tags: ["קטן", "סקרן", "אוהב לחפור"],
    dateAvailable: "2026-03-18",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "noaf-galil-nina-2026",
    name: "נינה",
    age: 1.5,
    ageGroup: "young",
    sex: "female",
    neutered: true,
    size: "medium",
    breedDisplay: "תערובת",
    weightKg: 13,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d0/German_Shepherd_-_DSC_0346_%2810096362833%29.jpg",
    shelterId: "noaf-galil",
    region: "north",
    description: "נינה כלבה עם מבט עמוק ונפש שקטה. היא לא הראשונה לבוא לאנשים חדשים, אבל ברגע שנוצר קשר — אינה מרפה. אוהבת ישיבה שקטה ליד הבעלים ולהסתכל על הטבע.",
    goodWith: ["cats", "dogs"],
    tags: ["שקט", "נאמן", "אוהב טבע"],
    dateAvailable: "2026-02-18",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  // ── haifa-bay-paws (north) ──
  {
    id: "haifa-bay-paws-nili-2026",
    name: "נילי",
    age: 3,
    ageGroup: "adult",
    sex: "female",
    neutered: true,
    size: "medium",
    breedSlug: "dalmatian",
    breedDisplay: "דלמטי מעורב",
    weightKg: 20,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/68/Sun_Dog_Dalmatian.jpg",
    shelterId: "haifa-bay-paws",
    region: "north",
    description: "נילי היא כוכבת הלכת של המקלט — כולם מכירים אותה. נקודותיה המיוחדות אינן רק חיצוניות; היא גם כלבה שמחה ומלאת חיים שמביאה אור לכל חדר. מחפשת בית פעיל.",
    goodWith: ["kids", "dogs"],
    tags: ["שמח", "ייחודי", "אנרגטי"],
    dateAvailable: "2026-03-05",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "haifa-bay-paws-shobi-2026",
    name: "שובי",
    age: 0.6,
    ageGroup: "puppy",
    sex: "male",
    neutered: false,
    size: "small",
    breedDisplay: "תערובת",
    weightKg: 4,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/18/2008-07-28_Dog_at_Frolick_Field.jpg",
    shelterId: "haifa-bay-paws",
    region: "north",
    description: "שובי גור קטן שנמצא ברחוב בחיפה עם עיניים עצובות וזנב מפזזח. עם כמה שבועות של חום ושגרה הפך לגורה אנרגטי ומחייך. מחפש מישהו שיאהב ללכת לפארק בבוקר.",
    goodWith: ["kids", "dogs", "cats"],
    tags: ["גורה", "חמוד", "שמח"],
    dateAvailable: "2026-05-05",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "haifa-bay-paws-chopi-2026",
    name: "צ'ופי",
    age: 6,
    ageGroup: "adult",
    sex: "male",
    neutered: true,
    size: "small",
    breedSlug: "shih-tzu",
    breedDisplay: "שי צו מעורב",
    weightKg: 8,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/df/Shihtzu_%28cropped%29.jpg",
    shelterId: "haifa-bay-paws",
    region: "north",
    description: "צ'ופי הוא שליט הספה. הגיע אלינו לאחר שבעלתו המבוגרת נפטרה ולא נמצאה משפחה שתקלוט אותו. הוא כלב מסורתי בית שמחפש חיק חם ובעלת שתחבב אותו.",
    goodWith: ["cats", "small-pets"],
    tags: ["מפונק", "אוהב בית", "רגוע"],
    dateAvailable: "2026-04-08",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "haifa-bay-paws-rex-2026",
    name: "רקס",
    age: 4,
    ageGroup: "adult",
    sex: "male",
    neutered: true,
    size: "giant",
    breedSlug: "rottweiler",
    breedDisplay: "רוטוויילר מעורב",
    weightKg: 50,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/26/Rottweiler_standing_facing_left.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    shelterId: "haifa-bay-paws",
    region: "north",
    description: "רקס הוא ענק בעל לב ענק. בחוץ נראה מרשים ואפילו מפחיד, אבל בבית הוא כלב משפחה רך ומאוזן. עבר עולם קשה לפני שהגיע אלינו ועכשיו מחפש שקט ויציבות.",
    goodWith: ["kids", "dogs"],
    tags: ["ענק", "מגן", "לב זהב"],
    dateAvailable: "2026-02-10",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  // ── jerusalem-paws (jerusalem) ──
  {
    id: "jerusalem-paws-sophie-2026",
    name: "סופי",
    age: 5,
    ageGroup: "adult",
    sex: "female",
    neutered: true,
    size: "medium",
    breedSlug: "poodle-mini",
    breedDisplay: "פודל מיניאטורי מעורב",
    weightKg: 7,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Full_attention_%288067543690%29.jpg/3840px-Full_attention_%288067543690%29.jpg",
    shelterId: "jerusalem-paws",
    region: "jerusalem",
    description: "סופי היא כלבה מתוחכמת ואלגנטית שנמסרה כשבעליה עבר לדיור מוגן. היא מאומנת היטב, מכירה פקודות בסיסיות ואפילו כמה טריקים. אידיאלית למשפחה עירונית.",
    goodWith: ["cats", "kids", "small-pets"],
    tags: ["מאומן", "אלגנטי", "נוח לתחזוקה"],
    dateAvailable: "2026-03-10",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "jerusalem-paws-ginger-2026",
    name: "ג'ינג'י",
    age: 1,
    ageGroup: "young",
    sex: "male",
    neutered: true,
    size: "small",
    breedSlug: "pomeranian",
    breedDisplay: "פומרניאן מעורב",
    weightKg: 4,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/ca/Pomeranian.JPG",
    shelterId: "jerusalem-paws",
    region: "jerusalem",
    description: "ג'ינג'י הגיע אלינו עם שיער ענן כתמתם ואישיות של כוכב. הוא אוהב תשומת לב ויצר קשר מהיר עם כל מבקר. ייהנה בבית עם נוכחות רבה ומשחקים.",
    goodWith: ["kids", "cats"],
    tags: ["חמוד", "רוצה תשומת לב", "קטן"],
    dateAvailable: "2026-04-18",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "jerusalem-paws-jackie-2026",
    name: "ג'קי",
    age: 7,
    ageGroup: "senior",
    sex: "female",
    neutered: true,
    size: "large",
    breedDisplay: "תערובת",
    weightKg: 29,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/34/Labrador_on_Quantock_%282175262184%29.jpg",
    shelterId: "jerusalem-paws",
    region: "jerusalem",
    description: "ג'קי היא אישה מבוגרת וחכמה שחיה בבית עם ילדים כל חייה. עכשיו שהמשפחה עברה לחו\"ל היא מחפשת בית חדש. היא מכירה את כל הפקודות ותהיה כלב מדהים לכל בית.",
    goodWith: ["kids", "dogs", "cats"],
    tags: ["מאומן", "מבוגר", "ניסיון עשיר"],
    dateAvailable: "2026-02-22",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "jerusalem-paws-boni-2026",
    name: "בוני",
    age: 2,
    ageGroup: "young",
    sex: "male",
    neutered: true,
    size: "medium",
    breedSlug: "boxer",
    breedDisplay: "בוקסר מעורב",
    weightKg: 26,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/6f/Male_fawn_Boxer_undocked.jpg",
    shelterId: "jerusalem-paws",
    region: "jerusalem",
    description: "בוני הוא בוקסר שמח שנמסר כשבעליו נולד לו ילד ולא יכל להתמודד עם הלחץ. הוא אוהב ילדים מאוד ואותם אוהבים אותו. עם קצת אילוף ייהנה בבית עם הרבה אהבה.",
    goodWith: ["kids", "dogs"],
    tags: ["אנרגטי", "אוהב ילדים", "צריך אילוף"],
    dateAvailable: "2026-03-22",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "jerusalem-paws-tova-2026",
    name: "טובה",
    age: 4,
    ageGroup: "adult",
    sex: "female",
    neutered: true,
    size: "medium",
    breedDisplay: "תערובת",
    weightKg: 14,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/bd/Golden_Retriever_Dukedestiny01_drvd.jpg",
    shelterId: "jerusalem-paws",
    region: "jerusalem",
    description: "טובה כלבה שקטה ואינטליגנטית שאוהבת לשחק חיפוש ולפתור חידות. היא מתחברת עמוק לבני האדם שלה ואוהבת מגע גוף. מתאימה לאנשים שרוצים כלב אמוציונלי ורגיש.",
    goodWith: ["kids", "cats", "dogs"],
    tags: ["חכם", "רגיש", "אמוציונלי"],
    dateAvailable: "2026-04-25",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  // ── judean-hills-haven (jerusalem) ──
  {
    id: "judean-hills-haven-ronit-2026",
    name: "רונית",
    age: 5,
    ageGroup: "adult",
    sex: "female",
    neutered: true,
    size: "medium",
    breedSlug: "border-collie",
    breedDisplay: "בורדר קולי מעורב",
    weightKg: 17,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e4/Border_Collie_600.jpg",
    shelterId: "judean-hills-haven",
    region: "jerusalem",
    description: "רונית כלבה חכמה מהגבעות היהודיות שהגיעה אלינו לאחר שבעליה נפטר. היא מבינה כל מילה ומגיבה בעיניים עמוקות. מחפשת בעל שיאהב לדבר איתה כמו עם חברה.",
    goodWith: ["kids", "dogs"],
    tags: ["חכם", "מבין הרבה", "נאמן"],
    dateAvailable: "2026-03-30",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "judean-hills-haven-bodo-2026",
    name: "בודו",
    age: 1.5,
    ageGroup: "young",
    sex: "male",
    neutered: true,
    size: "large",
    breedSlug: "malinois",
    breedDisplay: "מאלינואה מעורב",
    weightKg: 27,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/2f/04_-_Belgian_shepherd_dog_varieties_-_Groenendael%2CTervuren%2C_Malinois%2C_Laekenois.jpg",
    shelterId: "judean-hills-haven",
    region: "jerusalem",
    description: "בודו הוא כלב עם פוטנציאל עצום שזקוק לידיים מנוסות ולמשימות שמאתגרות אותו. נמסר אחרי שמאלן לא הצליח להתמודד עם כוחו. עם אילוף מקצועי יהיה כלב מרשים ומסור.",
    goodWith: ["kids"],
    tags: ["דרוש ניסיון", "כוחני", "חכם מאוד"],
    dateAvailable: "2026-04-12",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "judean-hills-haven-penina-2026",
    name: "פנינה",
    age: 9,
    ageGroup: "senior",
    sex: "female",
    neutered: true,
    size: "toy",
    breedSlug: "maltese",
    breedDisplay: "מלטז מעורב",
    weightKg: 3,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/94/Maltese_600.jpg",
    shelterId: "judean-hills-haven",
    region: "jerusalem",
    description: "פנינה היא אבן יקרה שמחפשת ידיים אוהבות. כלבה לבנה כשלג שנשארה לבד אחרי שבעלה נפטר. מסתפקת במעט ונותנת הרבה. תמצא את מקומה בבית שקט עם אנשים שמבינים ערך של נאמנות.",
    goodWith: ["cats", "small-pets"],
    tags: ["עדין", "מבוגר", "אוהב שקט"],
    dateAvailable: "2026-02-08",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  // ── beersheba-friends (south) ──
  {
    id: "beersheba-friends-amir-2026",
    name: "אמיר",
    age: 3,
    ageGroup: "adult",
    sex: "male",
    neutered: true,
    size: "medium",
    breedSlug: "canaan",
    breedDisplay: "כלב כנעני מעורב",
    weightKg: 19,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/fe/CanaanDogChakede.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    shelterId: "beersheba-friends",
    region: "south",
    description: "אמיר כלב מדבר עם רוח חופשית. הוא הסתובב בנגב כמה חודשים לפני שניצלנו אותו. מסתגל יפה לבית אבל אוהב טיולים ארוכים בטבע. מתאים לבית עם גינה.",
    goodWith: ["dogs", "kids"],
    tags: ["עצמאי", "אוהב טבע", "מסתגל"],
    dateAvailable: "2026-03-15",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "beersheba-friends-dana-2026",
    name: "דנה",
    age: 2,
    ageGroup: "young",
    sex: "female",
    neutered: true,
    size: "small",
    breedSlug: "schnauzer-mini",
    breedDisplay: "שנאוצר מיניאטורי מעורב",
    weightKg: 8,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/30/Miniature_Schnauzer_salt_%26_pepper_%28cropped%29.jpg",
    shelterId: "beersheba-friends",
    region: "south",
    description: "דנה כלבה בעלת שפם אופנתי ואישיות שקשה להתנגד לה. היא פיקחית ומאמנת עצמה ללא הרף. אוהבת אגוזי שקדיה ולצפות בטלוויזיה לצד הבעלים.",
    goodWith: ["kids", "cats"],
    tags: ["פיקח", "עצמאי", "נוח לאילוף"],
    dateAvailable: "2026-04-05",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "beersheba-friends-golem-2026",
    name: "גולם",
    age: 6,
    ageGroup: "adult",
    sex: "male",
    neutered: false,
    size: "giant",
    breedSlug: "great-dane",
    breedDisplay: "גרייט דיין מעורב",
    weightKg: 65,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e0/Dog_niemiecki_%C5%BC%C3%B3%C5%82ty_LM980.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    shelterId: "beersheba-friends",
    region: "south",
    description: "גולם הוא ענק שקט שאוהב לחסות בצל האוהלים. הגיע אלינו מחווה בנגב שנסגרה. נראה מאיים אבל הוא הנשמה הכי רכה במקלט. זקוק לבית עם מקום רב.",
    goodWith: ["kids", "dogs"],
    tags: ["ענק", "רגוע", "לב רך"],
    dateAvailable: "2026-02-05",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "beersheba-friends-tami-2026",
    name: "תמי",
    age: 1.5,
    ageGroup: "young",
    sex: "female",
    neutered: true,
    size: "medium",
    breedDisplay: "תערובת",
    weightKg: 15,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d0/German_Shepherd_-_DSC_0346_%2810096362833%29.jpg",
    shelterId: "beersheba-friends",
    region: "south",
    description: "תמי כלבה אוהבת חיים שנמצאה ליד בית ספר בבאר שבע. ילדי השכונה כינו אותה 'הכלבה של כולם'. מסתדרת מצוין עם ילדים ומה שהיא צריכה זה משפחה שתאמץ אותה סופית.",
    goodWith: ["kids", "dogs", "cats"],
    tags: ["אוהב ילדים", "חברותי", "שמח"],
    dateAvailable: "2026-04-20",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "beersheba-friends-luka-2026",
    name: "לוקה",
    age: 8,
    ageGroup: "senior",
    sex: "male",
    neutered: true,
    size: "large",
    breedDisplay: "תערובת",
    weightKg: 32,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/34/Labrador_on_Quantock_%282175262184%29.jpg",
    shelterId: "beersheba-friends",
    region: "south",
    description: "לוקה הוא ותיק שרואה כבר הרבה. הגיע אלינו לאחר שבעליו אושפז לתקופה ארוכה. הוא כלב נוח ורגוע, מסתפק בטיול יומי קצר ובמנוחה על השטיח. מגיע לו בית חם לשנים הנותרות.",
    goodWith: ["cats", "dogs"],
    tags: ["מבוגר", "שקט", "נוח"],
    dateAvailable: "2026-02-18",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "beersheba-friends-puppy-ori-2026",
    name: "אורי",
    age: 0.3,
    ageGroup: "puppy",
    sex: "male",
    neutered: false,
    size: "medium",
    breedDisplay: "תערובת",
    weightKg: 3,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/bd/Golden_Retriever_Dukedestiny01_drvd.jpg",
    shelterId: "beersheba-friends",
    region: "south",
    description: "אורי גור חום ורך שנולד לאם שנמצאה ברחוב. הוא עדיין קטן ורוצה לטפס על כולם. שם שנבחר עבורו כי מהרגע שנולד הביא אורה לכל המקלט.",
    goodWith: ["kids", "dogs"],
    tags: ["גורה", "חמוד", "רך"],
    dateAvailable: "2026-05-20",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  // ── negev-paws (south) ──
  {
    id: "negev-paws-shira-2026",
    name: "שירה",
    age: 4,
    ageGroup: "adult",
    sex: "female",
    neutered: true,
    size: "medium",
    breedSlug: "cattle-dog",
    breedDisplay: "כלב בקר אוסטרלי מעורב",
    weightKg: 18,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/cc/ACD-blue-spud.jpg",
    shelterId: "negev-paws",
    region: "south",
    description: "שירה כלבה כחלחלה עם עיניים חודרות ואינטליגנציה מעל הממוצע. היא אוהבת לעבוד ולהיות עסוקה. אם תיתנו לה משימה — היא תעשה אותה בהצטיינות. מושלמת לחיים בחוץ.",
    goodWith: ["kids", "dogs"],
    tags: ["חכם", "אנרגטי", "אוהב עבודה"],
    dateAvailable: "2026-03-08",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "negev-paws-ido-2026",
    name: "עידו",
    age: 2,
    ageGroup: "young",
    sex: "male",
    neutered: true,
    size: "large",
    breedDisplay: "תערובת",
    weightKg: 25,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/18/2008-07-28_Dog_at_Frolick_Field.jpg",
    shelterId: "negev-paws",
    region: "south",
    description: "עידו הגיע אלינו רזה ומותש מהמדבר. עם כמה חודשי טיפול הוא הפך לכלב בריא ושמח. אוהב לרוץ בין חולות הנגב ולשחק עם כלבים אחרים. מצוין לבית עם חצר.",
    goodWith: ["dogs", "kids"],
    tags: ["מבריא ועולה", "אנרגטי", "חברותי"],
    dateAvailable: "2026-04-15",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "negev-paws-liora-2026",
    name: "ליאורה",
    age: 6,
    ageGroup: "adult",
    sex: "female",
    neutered: true,
    size: "toy",
    breedSlug: "yorkshire",
    breedDisplay: "יורקשייר טרייר מעורב",
    weightKg: 3,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/41/%282_version%29_Grupp_3%2C_YORKSHIRETERRIER%2C_NO_UCH_SE_UCH_Oxzar_Amazing_Bel%E2%80%99s_Toffy_%2824310212305%29.jpg",
    shelterId: "negev-paws",
    region: "south",
    description: "ליאורה היא כלבה זעירה עם שיער משיי וגאווה של מלכה. הגיעה אלינו מבית שפינה לדירת קשישים. מחפשת בית שקט עם בעלת שתסרוק אותה בבוקר ותעניק לה את הכבוד המגיע לה.",
    goodWith: ["cats", "small-pets"],
    tags: ["קטן", "מפונק", "אלגנטי"],
    dateAvailable: "2026-03-25",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "negev-paws-tzvi-2026",
    name: "צבי",
    age: 1,
    ageGroup: "young",
    sex: "male",
    neutered: true,
    size: "large",
    breedSlug: "greyhound",
    breedDisplay: "גרייהאונד מעורב",
    weightKg: 29,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/ef/GraceTheGreyhound.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    shelterId: "negev-paws",
    region: "south",
    description: "צבי כלב מהיר כרוח שנמצא לאחר שברח מספינה. הוא שקט ורגוע בבית אבל בחוץ — רק הרוח תדביק אותו. כלב מיוחד שיצחיק ויפתיע כל בית.",
    goodWith: ["dogs", "cats"],
    tags: ["מהיר", "שקט בבית", "מיוחד"],
    dateAvailable: "2026-04-30",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  // ── back to tlv-dog-haven & sharon for more center dogs ──
  {
    id: "tlv-dog-haven-pita-2026",
    name: "פיתה",
    age: 3,
    ageGroup: "adult",
    sex: "male",
    neutered: true,
    size: "medium",
    breedSlug: "beagle",
    breedDisplay: "ביגל מעורב",
    weightKg: 12,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/55/Beagle_600.jpg",
    shelterId: "tlv-dog-haven",
    region: "center",
    description: "פיתה קיבל את שמו כי הוא עגול ורך. כלב שנמסר על ידי חייל שחזר מהמילואים ולא יכל לטפל בו. הוא מגיב יפה לאנשים, אוהב ריחות ויחייך לבעל שיוציא אותו לחפש עקבות.",
    goodWith: ["kids", "dogs"],
    tags: ["אוהב ריחות", "ידידותי", "קל לאילוף"],
    dateAvailable: "2026-03-28",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "tlv-dog-haven-ziv-2026",
    name: "זיו",
    age: 1,
    ageGroup: "young",
    sex: "male",
    neutered: true,
    size: "toy",
    breedSlug: "chihuahua",
    breedDisplay: "צ'יוואווה מעורב",
    weightKg: 2,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4c/Chihuahua1_bvdb.jpg",
    shelterId: "tlv-dog-haven",
    region: "center",
    description: "זיו קטן בגוף אבל ענק בביטחון עצמי. הוא עלה לנו מרחוב הים בתל אביב כשכולם נמנעו מלגעת בו. אחרי שבוע עם אנשים מטפלים נפתח לגמרי — ועכשיו אי אפשר להפסיק אותו.",
    goodWith: ["cats", "small-pets"],
    tags: ["קטן", "אמיץ", "מלא אישיות"],
    dateAvailable: "2026-05-08",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "sharon-rescue-hanita-2026",
    name: "חניתה",
    age: 5,
    ageGroup: "adult",
    sex: "female",
    neutered: true,
    size: "large",
    breedSlug: "samoyed",
    breedDisplay: "סמויד מעורב",
    weightKg: 24,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/18/Samojed00.jpg",
    shelterId: "sharon-rescue",
    region: "center",
    description: "חניתה היא כלבה לבנה כשלג עם חיוך שמח בכל עת. מגיעה מבית עם ילדים רבים ורגילה לרעש ולמולת. לא מתעייפת מחברת אנשים ותמיד שמחה לפגוש פנים חדשות.",
    goodWith: ["kids", "dogs", "cats"],
    tags: ["שמח", "לבן", "חברותי"],
    dateAvailable: "2026-04-03",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "sharon-rescue-bibi-2026",
    name: "ביבי",
    age: 0.5,
    ageGroup: "puppy",
    sex: "male",
    neutered: false,
    size: "small",
    breedDisplay: "תערובת",
    weightKg: 4,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/18/2008-07-28_Dog_at_Frolick_Field.jpg",
    shelterId: "sharon-rescue",
    region: "center",
    description: "ביבי הוא גור שחור קטן עם אוזניים גדולות מדי לגודלו ועיניים עמוקות מתחנן לאהבה. הגיע אלינו עם אחותו ונשאר לבד אחרי שהיא אומצה. מחכה לבית שיאהב אותו כמוהו.",
    goodWith: ["kids", "dogs"],
    tags: ["גורה", "שחור", "מחפש חברה"],
    dateAvailable: "2026-05-12",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "tlv-dog-haven-hadas-2026",
    name: "הדס",
    age: 2,
    ageGroup: "young",
    sex: "female",
    neutered: true,
    size: "medium",
    breedSlug: "shiba-inu",
    breedDisplay: "שיבא אינו מעורב",
    weightKg: 9,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/6b/Taka_Shiba.jpg",
    shelterId: "tlv-dog-haven",
    region: "center",
    description: "הדס כלבה יפנית בחזותה ועברייה בנפשה. היא עצמאית ומתנהגת כמו חתולה בכמה דברים — יושבת גבוה, שומרת על ניקיון ועושה מה שבא לה. בעל שמבין אותה ירגיש שזכה.",
    goodWith: ["cats"],
    tags: ["עצמאי", "נקי", "ייחודי"],
    dateAvailable: "2026-04-14",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "sharon-rescue-amos-2026",
    name: "עמוס",
    age: 7,
    ageGroup: "senior",
    sex: "male",
    neutered: true,
    size: "large",
    breedSlug: "labrador",
    breedDisplay: "לברדור מעורב",
    weightKg: 34,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/34/Labrador_on_Quantock_%282175262184%29.jpg",
    shelterId: "sharon-rescue",
    region: "center",
    description: "עמוס לברדור זהוב שכבר לא צעיר אבל עדיין שמח ומאושר. היה כלב עיוורים לשעבר ועדיין זוכר את כל ה'ישב', 'שכב', 'עמוד'. מחפש משפחה שתתן לו להזדקן בכבוד.",
    goodWith: ["kids", "dogs", "cats"],
    tags: ["מאומן", "רגוע", "מבוגר בכבוד"],
    dateAvailable: "2026-03-02",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "haifa-bay-paws-maya-2026",
    name: "מיה",
    age: 3,
    ageGroup: "adult",
    sex: "female",
    neutered: true,
    size: "medium",
    breedDisplay: "תערובת",
    weightKg: 13,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/34/Labrador_on_Quantock_%282175262184%29.jpg",
    shelterId: "haifa-bay-paws",
    region: "north",
    description: "מיה הגיעה אלינו מהנמל אחרי שנמצאה על ספינה. מסתבר שאהבת הים עברה גם אליה. אוהבת לישב ולהביט לאופק וגם סתם לשבת על אנשים. כלבה חמימה ומוסיפה שמחה.",
    goodWith: ["kids", "cats", "dogs"],
    tags: ["חמים", "שמח", "אוהב חברה"],
    dateAvailable: "2026-04-02",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "haifa-bay-paws-sammy-2026",
    name: "סמי",
    age: 1,
    ageGroup: "young",
    sex: "male",
    neutered: true,
    size: "small",
    breedSlug: "pug",
    breedDisplay: "פאג מעורב",
    weightKg: 8,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f3/Mops-duke-mopszucht-vom-maegdebrunnen.jpg",
    shelterId: "haifa-bay-paws",
    region: "north",
    description: "סמי עם הפנים הכבושות והנשימה הרועשת הוא קומיקאי מקצועי. אוהב לחקות את הבעלים, לשבת כמוהם ולהביט לטלוויזיה. קטן, חמוד ומצחיק — יוסיף הרבה שמחה לכל בית.",
    goodWith: ["kids", "cats", "small-pets"],
    tags: ["מצחיק", "חמוד", "שמח"],
    dateAvailable: "2026-04-28",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "judean-hills-haven-asher-2026",
    name: "אשר",
    age: 4,
    ageGroup: "adult",
    sex: "male",
    neutered: true,
    size: "medium",
    breedDisplay: "תערובת",
    weightKg: 16,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d0/German_Shepherd_-_DSC_0346_%2810096362833%29.jpg",
    shelterId: "judean-hills-haven",
    region: "jerusalem",
    description: "אשר כלב פשוט ומרגש בפשטותו. אין לו פריצות דרך גנאלוגיות אבל יש לו לב גדול ורצון לרצות. מסתדר עם כולם ועדיין לא נמצא לו הבית הנכון. אולי אתם?",
    goodWith: ["kids", "dogs", "cats"],
    tags: ["חברותי", "מסתגל", "מחפש בית"],
    dateAvailable: "2026-03-20",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "noaf-galil-yam-2026",
    name: "ים",
    age: 0.4,
    ageGroup: "puppy",
    sex: "male",
    neutered: false,
    size: "large",
    breedSlug: "golden",
    breedDisplay: "גולדן רטריבר מעורב",
    weightKg: 6,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/bd/Golden_Retriever_Dukedestiny01_drvd.jpg",
    shelterId: "noaf-galil",
    region: "north",
    description: "ים גור זהוב שנמצא על שפת הכינרת. שמו ניתן לו על שם הים הפנימי שבאגנו נמצא. הוא שמח, ים של אנרגיה ויגדל לכלב מרשים. המאמץ שבאילופו ישתלם פי מאה.",
    goodWith: ["kids", "dogs"],
    tags: ["גורה", "זהוב", "מרשים"],
    dateAvailable: "2026-05-18",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "beersheba-friends-kfir-2026",
    name: "כפיר",
    age: 2,
    ageGroup: "young",
    sex: "male",
    neutered: true,
    size: "large",
    breedSlug: "malinois",
    breedDisplay: "מאלינואה מעורב",
    weightKg: 28,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/2f/04_-_Belgian_shepherd_dog_varieties_-_Groenendael%2CTervuren%2C_Malinois%2C_Laekenois.jpg",
    shelterId: "beersheba-friends",
    region: "south",
    description: "כפיר הגיע מיחידה צבאית שהפסיקה את אימונו עקב ירידה בתקציב. הוא ממושמע ופקיד, אבל זקוק לבעל שיאתגר אותו ויתן לו מטרה. לא כלב לדירה קטנה ואורח חיים שקט.",
    goodWith: ["kids"],
    tags: ["ממושמע", "צריך אתגר", "דרוש ניסיון"],
    dateAvailable: "2026-04-10",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "sharon-rescue-yael-2026",
    name: "יעל",
    age: 5,
    ageGroup: "adult",
    sex: "female",
    neutered: true,
    size: "small",
    breedSlug: "cavalier",
    breedDisplay: "קוואליר קינג צ'ארלס מעורב",
    weightKg: 7,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5f/CarterBIS.Tiki.13.6.09.jpg",
    shelterId: "sharon-rescue",
    region: "center",
    description: "יעל היא נסיכה אמיתית עם מזג מתון ואוזניים שמחות. הגיעה אלינו מבית עם ילד אלרגי. היא אוהבת ישיבה שקטה ומסתגלת היטב לקצב הבית. כלבה מושלמת לכל גיל.",
    goodWith: ["cats", "kids", "small-pets", "dogs"],
    tags: ["עדין", "מסתגל", "לכל גיל"],
    dateAvailable: "2026-03-14",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
  {
    id: "negev-paws-ron-2026",
    name: "רון",
    age: 3,
    ageGroup: "adult",
    sex: "male",
    neutered: true,
    size: "medium",
    breedDisplay: "תערובת",
    weightKg: 14,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/bd/Golden_Retriever_Dukedestiny01_drvd.jpg",
    shelterId: "negev-paws",
    region: "south",
    description: "רון כלב נגבי מקורי שהסתובב ליד קיבוץ בנגב. הוא חמוד ורגוע, מכיר את השטח ואוהב לשמוע צלצול מפתחות — סימן שיוצאים לטיול. מחפש בית עם חוץ.",
    goodWith: ["dogs", "kids"],
    tags: ["נגבי", "שקט", "אוהב חוץ"],
    dateAvailable: "2026-03-05",
    contactUrl: "https://adopt.org.il",
    isExample: true,
  },
];

export function getDogById(id: string): AdoptableDog | undefined {
  return ADOPTABLE_DOGS.find((d) => d.id === id);
}

export function allDogIds(): string[] {
  return ADOPTABLE_DOGS.map((d) => d.id);
}
